"""
Indian brand lexicon: load data/indian_brands.json and merge into synonym_map.

Generated by build_indian_brands.py from Common Drug Codes for India (NRCeS/C-DAC,
CC BY 4.0 - attribute C-DAC/NRCeS) and the community Indian-Medicine-Dataset.
"""

import json
import logging
import re
from pathlib import Path

logger = logging.getLogger(__name__)

LEXICON_FILE = Path(__file__).resolve().parent.parent / 'data' / 'indian_brands.json'

# Junk-surface guard (mirrors build_indian_brands emission filter): short
# uncurated fragments and salt/concentration artifacts must never enter the
# synonym map, even if a stale lexicon file still carries them.
_JUNK_RES = [re.compile(r'^ns(-|%| )?'), re.compile(r'[%\[\(/:+]'),
            re.compile(r'\d{5,}-\d{2}-\d'), re.compile(r'^[^a-z]+$'),
            re.compile(r'stayhappi')]


def _ok_surface(surface: str, priority: bool) -> bool:
    t = (surface or '').strip().lower()
    if not t or len(t) <= 2 or len(t) > 40:
        return False
    if any(p.search(t) for p in _JUNK_RES):
        return False
    if len(t) <= 4 and not priority:
        return False
    return True


def load_brand_lexicon() -> dict:
    """Return {brand_key: {ingredients, variants, ...}} or {} when absent."""
    if not LEXICON_FILE.exists():
        logger.info("No Indian brand lexicon at %s", LEXICON_FILE)
        return {}
    try:
        with open(LEXICON_FILE, encoding='utf-8') as f:
            data = json.load(f)
        return data if isinstance(data, dict) else {}
    except Exception as e:
        logger.warning("Failed to load brand lexicon: %s", e)
        return {}


def apply_brand_lexicon(synonym_map: dict) -> int:
    """
    Merge Indian brand mappings into a synonym_map (brand entries win on
    conflict so freshly built data beats stale manual overrides).
    Returns the number of keys written.
    """
    lex = load_brand_lexicon()
    if not lex:
        return 0
    written = 0
    skipped = 0
    for brand, entry in lex.items():
        ings = [str(i).strip().lower() for i in entry.get('ingredients', [])
                if str(i or '').strip()]
        if not ings:
            continue
        val = ings[0] if len(ings) == 1 else ings
        pri = bool(entry.get('priority'))
        keys = {str(brand).strip().lower()}
        keys.update(str(v).strip().lower() for v in entry.get('variants', []))
        keys.discard('')
        for k in keys:
            if not _ok_surface(k, pri):
                skipped += 1
                continue
            synonym_map[k] = val
            written += 1
    logger.info("Merged %d Indian brand aliases (%d concepts) into synonym_map "
                "(skipped %d junk surfaces)",
                written, len(lex), skipped)
    return written
